steps:
  # [START cloudbuild_python_dependencies_yaml]
  # Install dependencies
  - name: python
    entrypoint: pip
    args: ["install", "-r", "api/requirements.txt"]
  # [END cloudbuild_python_dependencies_yaml]

  # [START cloudbuild_python_image_yaml]
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
           'gcr.io/$PROJECT_ID/nlp-api-image:${SHORT_SHA}', '.']
  # [END cloudbuild_python_image_yaml]

  # [START cloudbuild_python_push_yaml]
  # Docker push to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',  'gcr.io/$PROJECT_ID/nlp-api-image:${SHORT_SHA}']
  # [END cloudbuild_python_push_yaml]
  
  # [START cloudbuild_python_deploy_yaml]
  # Deploy to Cloud Run
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'nlp-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/nlp-api-image:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
  # [END cloudbuild_python_deploy_yaml]
