steps:

  # [START cloudbuild_python_image_yaml]
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
           'gcr.io/$PROJECT_ID/$_IMAGE:$COMMIT_SHA', '.']
  # [END cloudbuild_python_image_yaml]

  # [START cloudbuild_python_push_yaml]
  # Docker push to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',  'gcr.io/$PROJECT_ID/$_IMAGE:$COMMIT_SHA']
  # [END cloudbuild_python_push_yaml]
  
  # [START cloudbuild_python_deploy_yaml]
  # Deploy to Cloud Run
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '$_RESOURCE_NAME'
      - '--image'
      - 'gcr.io/$PROJECT_ID/$_IMAGE:$COMMIT_SHA'
      - '--region'
      - '$_REGION'
      - '--port'
      - '$_PORT'
  # [END cloudbuild_python_deploy_yaml]
images:
  - 'gcr.io/$PROJECT_ID/$_IMAGE:$COMMIT_SHA'